id: P005555
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1222
  title: མདོ་སྡེ་སྤྱིའི་རྣམ་བཞག་མདོར་བསྡུས་
  author: ''
  volumes:
    adb49383f6f6486c91a01f3ac1dfa803:
      image_group_id: I1CZ1683
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
