id: I7DCCD287
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:33:25+00:00'
last_modified: '2022-06-08T04:53:15.421326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1222
  title: མདོ་སྡེ་སྤྱིའི་རྣམ་བཞག་མདོར་བསྡུས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D466:
      image_group_id: I1CZ1683
      title: ''
      total_pages: 76
      order: 1
      base_file: D466.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
